language: generic

matrix:
  include:
    - os: osx
      before_install:
        - pyenv install 3.5
        - pyenv install 3.6
        - pyenv install 3.7
        - pyenv global 3.5

install: python -m pip install wheel scikit-build ninja
script: python setup.py bdist_wheel