language: generic
if: tag IS present

matrix:
  include:
    - os: osx
      osx_image: xcode11
      before_install:
        - export PATH="$HOME/.pyenv/shims:$HOME/.pyenv/bin:$PATH"
        - brew update && brew upgrade pyenv
        - eval "$(pyenv init -)"
        - pyenv install --list
        - pyenv install 3.5.7
        - pyenv install 3.6.9
        - pyenv install 3.7.4
        - pyenv install 3.8.6
        - pyenv install 3.9.0
script:
  - pyenv global 3.5.7
  - python -m pip install scikit-build ninja
  - python setup.py bdist_wheel
  - pyenv global 3.6.9
  - python -m pip install scikit-build ninja
  - python setup.py bdist_wheel
  - pyenv global 3.7.4
  - python -m pip install scikit-build ninja
  - python setup.py bdist_wheel
  - pyenv global 3.8.6
  - python -m pip install scikit-build ninja
  - python setup.py bdist_wheel
  - pyenv global 3.9.0
  - python -m pip install scikit-build ninja
  - python setup.py bdist_wheel
deploy:
  provider: releases
  api_key:
    secure: "VAxC+6CYI2T77q9yrbgfALfDOhbD7o3xeJ0xPPPmladZVwwrv3VANBRMD5ZNF7Ayh/U2G17Om1W4/MOwWI7zHxi3ASTYshxUsS9H6PDZgJSMaXFhR35s3mnVCordbap+O4xWCBA+85aZDEC2lWLlBwQunnjmuBw84mfQTkkv5w/D8zpvXJwsjFZYHyv209+7WPYjOQ+qFEpcDiVUP/l+gCMv9WASANGRjlUiNPhm5kIZwo5Bjl7t8yXIkYlt4V/7UQAL7EnnSKvykl85v/UDEUp+CroQ8WzE5gYMPtLrr8gTFPKp2jTLEGKl3r1R95yd83FQtVY+mSBI6goh/B82wjA3LmKvO6/VymF+y3UDNgQW/ZcLCqM+TD9dwEvTQJ0qiRSgNEfG3mqUmUTDRal7Y6igZyz9LQfb6Ue4iJ/i7LGRJQ9XfMG4ziy19cNm9MaaxZw/5fTlPP8ohvdKSzI5FSWQEw2kT4peooB7BYtqLeETX8IRyVNXGUCQzkQCkUqreEPn1D19SX3uXn1tQeicgLWf+v//zl6V1gSwc6XTYs0JaLdomcU5W7oXOLJL5Vp78wZrnFqDxE0W6QX48XoZ5SLiNZ8LV4cttH5oYObReuYHbMDgToelZoy2WdNiqlBFIeak9O4hOcB1mZcaPoREWXfrUoyA0HBFwlhBhfWXVWA="
  skip_cleanup: True
  file_glob: True
  file: dist/*
  on:
    tags: true
    all_branches: true
