skip_non_tags: true
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

install:
  # We need wheel installed to build wheels
  - cmd: set PATH=%PYTHON%;%PATH%
  - cmd: "%PYTHON%\\python.exe -m pip install --upgrade setuptools wheel"
  - cmd: "%PYTHON%\\python.exe -m pip install wheel scikit-build ninja"

build: off

test_script:
  - cmd: "%PYTHON%\\python.exe setup.py bdist_wheel"
  - sh: docker run --rm -v $(pwd):/io quay.io/pypa/manylinux1_x86_64 /bin/bash /io/build_wheels.sh

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.