name: Python build

on: workflow_dispatch
jobs:
  build:
    strategy:
          matrix:
            python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10', '3.11' ]
            os: ['windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel cmake
        pip install scikit-build ninja
        python setup.py bdist_wheel
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: "elkai-${{ matrix.os }}-${{ matrix.python-version }}.whl"
        path: dist/*.whl

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Python wheels manylinux build
      uses: pypa/cibuildwheel@v2.12.3
      env:
        CIBW_ARCHS: auto64  # only 64-bit
        CIBW_SKIP: "pp* *-musllinux_*"  # no PyPy builds
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014  # centos 7
        CIBW_BEFORE_BUILD: python -m pip install scikit-build cmake
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: "elkai-manylinux"
        path: wheelhouse/*.whl
