name: Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
          matrix:
            python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]
            os: ['windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel cmake
        pip install scikit-build ninja
        python setup.py bdist_wheel
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: "elkai-${{ matrix.os }}-${{ matrix.python-version }}.whl"
        path: dist/*.whl
